#!/bin/bash

echo "🚂 מדריך להעלאה ל-Railway..."
echo ""

echo "📋 שלבים להשלמה:"
echo ""
echo "1. 🎯 היכנס ל-railway.app"
echo "2. 🔐 התחבר עם GitHub"
echo "3. ➕ לחץ 'New Project'"
echo "4. 📦 בחר 'Deploy from GitHub repo'"
echo "5. 🔍 חפש את telegram-monitor שלך"
echo "6. ⚙️ הגדר משתני סביבה:"
echo ""
echo "   API_ID = 29517731"
echo "   API_HASH = 1ea4799dac3759058d07f2508979ecb2"
echo "   PHONE = +972508585661"
echo "   WEBHOOK_URL = https://hook.eu1.make.com/xngg9dxi7nc0x5q5jhshb74xmhfpeg06"
echo ""
echo "7. 🔧 הגדר Build:"
echo "   Build Command: pip install -r requirements.txt"
echo "   Start Command: python3 stable_monitor.py"
echo ""
echo "8. 🚀 לחץ 'Deploy Now'"
echo ""
echo "9. 📊 בדוק לוגים:"
echo "   - לחץ על 'Deployments'"
echo "   - לחץ על ה-deployment האחרון"
echo "   - לחץ 'View Logs'"
echo ""
echo "10. 🔐 אימות ראשוני:"
echo "    - שלח הודעה לטלגרם עם קוד אימות"
echo "    - הזן את הקוד בלוגים"
echo ""
echo "✅ אחרי שתסיים - התוכנה תרוץ 24/7!"
echo ""
echo "📖 לפרטים נוספים, ראה: RAILWAY_GUIDE.md" 